import type { CategoryItem, AnnouncementItem, NavigationLink } from '@/types';

export const ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: '1',
    text: '⚡ FESTIVE MONSOON SALE: Up to 40% OFF RTX 5090 Rigs & OLED Displays + No-Cost EMI',
    code: 'INDIA2026',
    linkText: 'Shop Indian Deals',
    linkUrl: '/products?sale=true',
    badge: 'LIMITED OFFER',
  },
  {
    id: '2',
    text: '🚀 FREE BlueDart Air Shipping & 18% GST Business Invoice Input across all 28 Indian States',
    linkText: 'Claim GST Credit',
    linkUrl: '/about',
    badge: 'GST COMPLIANT',
  },
  {
    id: '3',
    text: '🎮 Build Your Custom Liquid-Cooled Rig with 24-Month EMI starting @ ₹4,999/mo',
    linkText: 'Configure Custom PC',
    linkUrl: '/categories/custom-pcs',
    badge: 'NO-COST EMI',
  },
];

export const NAV_LINKS: NavigationLink[] = [
  { label: 'Store', href: '/products' },
  { label: 'Categories', href: '/categories', isMega: true },
  { label: 'Custom PCs', href: '/categories/custom-pcs', badge: 'BUILD' },
  { label: 'Deals & Outlet', href: '/products?discount=true', badge: 'SALE' },
  { label: 'About', href: '/about' },
];

export const MEGA_CATEGORIES: CategoryItem[] = [
  {
    id: 'laptops',
    name: 'Laptops & MacBooks',
    slug: 'laptops',
    description: 'High-performance workstations for creators, developers & gamers in India',
    icon: 'Laptop',
    itemCount: 42,
    featuredProduct: {
      id: 'titan-pro-m4',
      title: 'TechNest Titan Pro M4 Max (64GB RAM, 2TB SSD)',
      image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop',
      price: 249990,
      tag: 'FLAGSHIP',
    },
    subcategories: [
      { name: 'Gaming Laptops', slug: 'gaming-laptops', badge: 'RTX 5090' },
      { name: 'Creator Workstations', slug: 'creator-laptops' },
      { name: 'Ultrabooks & Slim', slug: 'ultrabooks' },
      { name: 'MacBook Pro & Air', slug: 'macbooks', badge: 'M4 Series' },
      { name: 'Refurbished & Certified', slug: 'refurbished-laptops' },
    ],
  },
  {
    id: 'gaming-pcs',
    name: 'Gaming PCs & Workstations',
    slug: 'gaming-pcs',
    description: 'Pre-built and custom desktop rigs engineered for extreme performance',
    icon: 'Monitor',
    itemCount: 38,
    featuredProduct: {
      id: 'apex-beast-v2',
      title: 'Apex Beast Ultra - Core i9 14900KS + RTX 5090 Liquid Cooled',
      image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?q=80&w=800&auto=format&fit=crop',
      price: 329990,
      tag: 'BESTSELLER',
    },
    subcategories: [
      { name: 'Ultra Gaming PCs', slug: 'ultra-gaming-pcs', badge: '4K Ready' },
      { name: 'AI & Data Science Rigs', slug: 'ai-workstations' },
      { name: 'Mini-ITX Compact Builds', slug: 'mini-itx-pcs' },
      { name: 'Custom Liquid Loop', slug: 'custom-pcs', badge: 'Custom' },
    ],
  },
  {
    id: 'monitors',
    name: 'Displays & OLED Monitors',
    slug: 'monitors',
    description: 'Ultra-wide 240Hz OLED and color-accurate 4K monitors with GST credit',
    icon: 'Tv',
    itemCount: 29,
    featuredProduct: {
      id: 'horizon-49-oled',
      title: 'TechNest Horizon 49" QD-OLED 240Hz Curved Display',
      image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop',
      price: 109990,
      tag: '240Hz OLED',
    },
    subcategories: [
      { name: '4K OLED Gaming Monitors', slug: 'oled-monitors', badge: 'NEW' },
      { name: 'Ultrawide 32:9 & 21:9', slug: 'ultrawide-monitors' },
      { name: 'Professional Color-Accurate', slug: 'creator-monitors' },
      { name: 'Dual Monitor Bundles', slug: 'monitor-bundles' },
    ],
  },
  {
    id: 'peripherals',
    name: 'Keyboards & Gaming Mice',
    slug: 'peripherals',
    description: 'Custom mechanical keyboards, magnetic switches, and ultra-light precision mice',
    icon: 'Keyboard',
    itemCount: 54,
    featuredProduct: {
      id: 'cyberblade-8k',
      title: 'CyberBlade Pro 8K Hz Rapid Trigger Custom Keyboard',
      image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800&auto=format&fit=crop',
      price: 17990,
      tag: '8000Hz',
    },
    subcategories: [
      { name: 'Custom Mechanical Keyboards', slug: 'mechanical-keyboards', badge: 'Hot-Swap' },
      { name: 'Magnetic Rapid-Trigger Keyboards', slug: 'rapid-trigger' },
      { name: 'Wireless Ultra-Light Mice', slug: 'gaming-mouse' },
      { name: 'Audiophile Desk Pads', slug: 'desk-pads' },
    ],
  },
  {
    id: 'audio',
    name: 'Audio & Studio Sound',
    slug: 'audio',
    description: 'Spatial audio headsets, planar magnetic headphones & XLR microphones',
    icon: 'Headphones',
    itemCount: 31,
    featuredProduct: {
      id: 'studio-pro-headset',
      title: 'TechNest Studio Master Wireless Spatial DAC Headset',
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
      price: 28990,
      tag: 'HI-RES AUDIO',
    },
    subcategories: [
      { name: 'Wireless Gaming Headsets', slug: 'headphones' },
      { name: 'Studio Reference Headphones', slug: 'studio-headphones', badge: 'Planar' },
      { name: 'XLR & USB Microphones', slug: 'microphones' },
      { name: 'Hi-Fi Bookshelf Speakers', slug: 'speakers' },
    ],
  },
  {
    id: 'accessories',
    name: 'Mobile, Storage & Networking',
    slug: 'accessories',
    description: 'Thunderbolt 5 docks, NVMe Gen5 SSDs, Wi-Fi 7 routers & smart devices',
    icon: 'Cpu',
    itemCount: 65,
    featuredProduct: {
      id: 'velocity-gen5-ssd',
      title: 'VelocityX 4TB PCIe 5.0 NVMe SSD (14,000 MB/s)',
      image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?q=80&w=800&auto=format&fit=crop',
      price: 32990,
      tag: 'GEN 5 SSD',
    },
    subcategories: [
      { name: 'Smartphones & Tablets', slug: 'smartphones' },
      { name: 'Gen5 PCIe NVMe Storage', slug: 'storage' },
      { name: 'Wi-Fi 7 Enterprise Routers', slug: 'networking' },
      { name: 'Thunderbolt 5 Docks & Cables', slug: 'accessories' },
    ],
  },
];
