import type { Product, Testimonial } from '@/types';

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'titan-pro-m4',
    name: 'TechNest Titan Pro M4 Max Studio Laptop',
    slug: 'titan-pro-m4-max',
    category: 'Laptops',
    categorySlug: 'laptops',
    brand: 'TechNest',
    price: 249990,
    originalPrice: 279990,
    rating: 4.9,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1000&auto=format&fit=crop',
    specs: ['Apple M4 Max (16-Core)', '64GB Unified RAM', '2TB Gen4 SSD', '16.2" Liquid Retina XDR 120Hz'],
    inStock: true,
    stockCount: 12,
    isNew: true,
    isBestseller: true,
    isFeatured: true,
    discountPercentage: 11,
    description: 'Designed for AI developers, 3D artists, and software engineers in India who demand uncompromised desktop-grade performance on the go with 18% GST credit capability.',
    emiStartingAt: 10416,
    warrantyYears: 2,
  },
  {
    id: 'apex-beast-v2',
    name: 'Apex Beast Ultra RTX 5090 Liquid-Cooled Desktop',
    slug: 'apex-beast-ultra-rtx-5090',
    category: 'Gaming PCs',
    categorySlug: 'gaming-pcs',
    brand: 'Apex',
    price: 329990,
    originalPrice: 369990,
    rating: 5.0,
    reviewCount: 89,
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?q=80&w=1000&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?q=80&w=1000&auto=format&fit=crop',
    specs: ['Intel Core i9 14900KS', 'NVIDIA RTX 5090 32GB', '64GB DDR5 7200MHz', '360mm AIO Custom Loop'],
    inStock: true,
    stockCount: 5,
    isNew: true,
    isBestseller: true,
    isFeatured: true,
    discountPercentage: 11,
    description: 'The ultimate liquid-cooled monster built to dominate 4K high refresh rate gaming, deep learning LLM training, and 8K rendering.',
    emiStartingAt: 13749,
    warrantyYears: 2,
  },
  {
    id: 'horizon-49-oled',
    name: 'Horizon 49" QD-OLED 240Hz Ultrawide Curved Display',
    slug: 'horizon-49-qd-oled-240hz',
    category: 'Monitors',
    categorySlug: 'monitors',
    brand: 'TechNest',
    price: 109990,
    originalPrice: 129990,
    rating: 4.8,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1000&auto=format&fit=crop',
    specs: ['49" 5120x1440 Dual QHD', '240Hz 0.03ms GTG', 'Quantum Dot OLED', 'KVM Switch + 90W Type-C'],
    inStock: true,
    stockCount: 18,
    isBestseller: true,
    isFeatured: true,
    discountPercentage: 15,
    description: 'Immerse yourself in a panoramic 1800R curved QD-OLED canvas with infinite contrast ratios and zero ghosting.',
    emiStartingAt: 4583,
    warrantyYears: 3,
  },
  {
    id: 'cyberblade-8k',
    name: 'CyberBlade Pro 8K Rapid Trigger Magnetic Keyboard',
    slug: 'cyberblade-pro-8k-rapid-trigger',
    category: 'Keyboards',
    categorySlug: 'peripherals',
    brand: 'CyberBlade',
    price: 17990,
    originalPrice: 19990,
    rating: 4.9,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=1000&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1000&auto=format&fit=crop',
    specs: ['8000Hz Polling Rate', 'Hall Effect Magnetic Switches', '0.1mm Adjustable Actuation', 'CNC Aluminum Chassis'],
    inStock: true,
    stockCount: 40,
    isNew: true,
    isFeatured: true,
    discountPercentage: 10,
    description: 'Esports-grade rapid trigger keyboard featuring magnetic Hall Effect switches for instant stop-and-shoot accuracy.',
    emiStartingAt: 1499,
    warrantyYears: 1,
  },
  {
    id: 'studio-pro-headset',
    name: 'Studio Master Wireless Planar Magnetic Headset',
    slug: 'studio-master-wireless-headset',
    category: 'Audio',
    categorySlug: 'audio',
    brand: 'TechNest',
    price: 28990,
    originalPrice: 32990,
    rating: 4.9,
    reviewCount: 95,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=1000&auto=format&fit=crop',
    specs: ['90mm Planar Drivers', 'Lossless 2.4GHz + BT 5.3', 'LDAC & Spatial Audio', '50-Hour Battery Life'],
    inStock: true,
    stockCount: 22,
    isFeatured: true,
    discountPercentage: 12,
    description: 'Audiophile-grade wireless planar headphones delivering crystal-clear spatial imaging and natural acoustic response.',
    emiStartingAt: 2415,
    warrantyYears: 2,
  },
  {
    id: 'velocity-gen5-ssd',
    name: 'VelocityX 4TB PCIe 5.0 NVMe SSD (14,000 MB/s)',
    slug: 'velocityx-4tb-pcie-5-nvme-ssd',
    category: 'Storage',
    categorySlug: 'accessories',
    brand: 'VelocityX',
    price: 32990,
    originalPrice: 36990,
    rating: 4.8,
    reviewCount: 78,
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?q=80&w=1000&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1551645120-d70bfe84c826?q=80&w=1000&auto=format&fit=crop',
    specs: ['14,000 MB/s Sequential Read', '12,000 MB/s Sequential Write', 'Custom Graphene Heatsink', '3000 TBW Endurance'],
    inStock: true,
    stockCount: 30,
    isFeatured: true,
    discountPercentage: 11,
    description: 'Blazing-fast Gen5 NVMe storage engineered for instant game load times and massive 8K video timelines.',
    emiStartingAt: 2749,
    warrantyYears: 5,
  },
  {
    id: 'rog-zephyrus-g16',
    name: 'ROG Zephyrus G16 OLED Gaming Laptop',
    slug: 'rog-zephyrus-g16-oled',
    category: 'Laptops',
    categorySlug: 'laptops',
    brand: 'Asus',
    price: 199990,
    originalPrice: 229990,
    rating: 4.8,
    reviewCount: 164,
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop',
    specs: ['Intel Core Ultra 9 185H', 'RTX 4080 12GB', '32GB LPDDR5X', '16" 2.5K 240Hz OLED'],
    inStock: true,
    stockCount: 8,
    isBestseller: true,
    discountPercentage: 13,
    description: 'Sleek CNC aluminum chassis equipped with a vibrant 240Hz ROG Nebula OLED display.',
    emiStartingAt: 8333,
    warrantyYears: 2,
  },
  {
    id: 'viper-v3-pro-mouse',
    name: 'Viper V3 Pro 8000Hz Ultra-Light Wireless Mouse',
    slug: 'viper-v3-pro-wireless-mouse',
    category: 'Peripherals',
    categorySlug: 'peripherals',
    brand: 'Razer',
    price: 12990,
    originalPrice: 14990,
    rating: 4.9,
    reviewCount: 420,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=1000&auto=format&fit=crop',
    specs: ['54g Ultra-Lightweight', 'Focus Pro 35K Gen-2 Optical Sensor', 'True 8000Hz Wireless Polling', '95 Hours Battery'],
    inStock: true,
    stockCount: 65,
    isBestseller: true,
    discountPercentage: 13,
    description: 'The preferred ultra-light wireless gaming mouse designed alongside world champion esports pros.',
    emiStartingAt: 1082,
    warrantyYears: 2,
  },
];

export const BRANDS = [
  { name: 'Apple India', logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg' },
  { name: 'NVIDIA India', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg' },
  { name: 'Intel', logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Intel_logo_%282020%29.svg' },
  { name: 'AMD India', logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/AMD_Logo.svg' },
  { name: 'Corsair', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Corsair_Components_logo.svg' },
  { name: 'Logitech G', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Logitech_logo.svg' },
  { name: 'ASUS ROG India', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/ASUS_Logo.svg' },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Aarav Sharma',
    role: 'Lead AI Infrastructure Engineer',
    company: 'Bengaluru Tech Park',
    city: 'Bengaluru, Karnataka',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    content: 'TechNest delivered our RTX 5090 liquid-cooled workstation in Bengaluru in under 24 hours via BlueDart Air. The 18% GST input credit saved our startup ₹59,000!',
    rating: 5,
    verified: true,
    productBought: 'Apex Beast Ultra RTX 5090',
  },
  {
    id: '2',
    name: 'Priya Nair',
    role: 'Senior Game Director & Streamer',
    company: 'Vanguard Gaming',
    city: 'Mumbai, Maharashtra',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop',
    content: 'The Horizon 49" QD-OLED paired with No-Cost EMI via HDFC credit card made upgrading my Mumbai stream setup seamless. Exceptional customer support.',
    rating: 5,
    verified: true,
    productBought: 'Horizon 49" QD-OLED Display',
  },
  {
    id: '3',
    name: 'Vikramaditya Roy',
    role: 'Staff Systems Architect',
    company: 'Gurugram Tech Hub',
    city: 'Gurugram, NCR',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    content: 'Ordering the Titan Pro M4 Max through TechNest was effortless. UPI payment via PhonePe was instant and the laptop arrived with 2-Year official warranty.',
    rating: 5,
    verified: true,
    productBought: 'Titan Pro M4 Max Studio Laptop',
  },
];

export const FAQ_ITEMS = [
  {
    question: 'How fast is BlueDart Air delivery across India and Tier 1 / Tier 2 cities?',
    answer: 'Orders placed before 3 PM IST ship same-day via BlueDart Air or Delhivery Express. Metro cities (Bengaluru, Mumbai, Delhi NCR, Hyderabad, Chennai, Pune, Kolkata) receive delivery within 24–48 hours.',
  },
  {
    question: 'How does 18% GST Business Invoice & Input Tax Credit (ITC) work?',
    answer: 'Enter your valid 15-digit GSTIN number at checkout. We issue an official Tax Invoice with your company name & GSTIN so you can claim full 18% GST Input Credit on your enterprise IT hardware purchases.',
  },
  {
    question: 'What No-Cost EMI options are supported for Indian customers?',
    answer: 'We support 3, 6, 9, and 12-month No-Cost EMI options across major Indian credit & debit cards (HDFC, ICICI, SBI, Axis, Kotak, Amazon Pay ICICI) as well as Bajaj Finserv cardless EMI.',
  },
  {
    question: 'What official warranty and door-step service support is included in India?',
    answer: 'All products sold on TechNest carry official brand warranties in India with door-step pickup and return support. Custom liquid-cooled rigs include a 2-Year TechNest On-Site Replacement Warranty.',
  },
];
