apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: technest-azure-keyvault
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "63473a46-a621-442b-bef9-5f43763899bd"
    keyvaultName: "kv-technest-shwetaank"
    tenantId: "8c286706-4769-4a2a-b614-228f54eb6b3e"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: resend-api-key
          objectType: secret
  secretObjects:
    - secretName: technest-secrets
      type: Opaque
      data:
        - objectName: database-url
          key: database-url
        - objectName: resend-api-key
          key: resend-api-key
