name: TechNest CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test Applications
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js 24 Environment
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install & Build Frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Install, Build & Test Backend
        env:
          DATABASE_URL: "postgresql://postgres.jgcvqbjveevmibehceym:Shwetank%40123@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
          DIRECT_URL: "postgresql://postgres.jgcvqbjveevmibehceym:Shwetank%40123@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
          SUPABASE_URL: "https://jgcvqbjveevmibehceym.supabase.co"
          SUPABASE_SERVICE_ROLE_KEY: "sb_publishable__mneBqzqnNOPM0MCSYC9KA_TDbsET6B"
          JWT_SECRET: "technest_production_jwt_signing_secret_987654321"
        run: |
          cd server
          npm install
          npm run build
          npm test
