name: TechNest Enterprise CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test Applications
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js 24 Environment
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install & Build Frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Install, Build & Test Backend
        env:
          DATABASE_URL: "postgresql://postgres.jgcvqbjveevmibehceym:Shwetank%40123@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
          DIRECT_URL: "postgresql://postgres.jgcvqbjveevmibehceym:Shwetank%40123@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
          SUPABASE_URL: "https://jgcvqbjveevmibehceym.supabase.co"
          SUPABASE_SERVICE_ROLE_KEY: "sb_publishable__mneBqzqnNOPM0MCSYC9KA_TDbsET6B"
          JWT_SECRET: "technest_production_jwt_signing_secret_987654321"
        run: |
          cd server
          npm install
          npm run build
          npm test

  docker-build-push:
    name: Build Docker Images & Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/technest-client:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/technest-client:latest -f Dockerfile.client .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/technest-client:latest

      - name: Build & Push Backend Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/technest-server:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/technest-server:latest -f Dockerfile.server .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/technest-server:latest

      - name: Set AKS Context & Deploy Manifests
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RG }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s/server-deployment.yaml
          kubectl apply -f k8s/client-deployment.yaml
